name: "update translations"
on:
  push:
    branches:
      - master
    paths:
      - 'selfdrive/ui/**'
  workflow_dispatch:

env:
  BASE_IMAGE: openpilot-base
  BUILD: selfdrive/test/docker_build.sh base
  RUN: docker run --shm-size 2G -v $PWD:/tmp/openpilot -w /tmp/openpilot -e CI=1 -e PYTHONWARNINGS=error -e FILEREADER_CACHE=1 -e PYTHONPATH=/tmp/openpilot -e NUM_JOBS -e JOB_ID -e GITHUB_ACTION -e GITHUB_REF -e GITHUB_HEAD_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -v $GITHUB_WORKSPACE/.ci_cache/scons_cache:/tmp/scons_cache -v $GITHUB_WORKSPACE/.ci_cache/comma_download_cache:/tmp/comma_download_cache -v $GITHUB_WORKSPACE/.ci_cache/openpilot_cache:/tmp/openpilot_cache $BASE_IMAGE /bin/bash -c

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/setup-with-retry
      - name: Update translations
        run: |
          ${{ env.RUN }} "python3 selfdrive/ui/update_translations.py"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "[GHA] Update translations"
          title: "Update translations"
          body: "Automated PR to update translations"
          branch: "update-translations"
          base: "master"
          delete-branch: true